### ISSUE TITLE
paginated user error on empty people

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#1172]
with an empty people list (that seems strange) I am seeing this server error when visiting the admin /people page
```
7:42:20 PM server.1               |  Error: Resolve function for "PageInfo.total" returned undefined
7:42:20 PM server.1               |      at /home/sky/sb/moveon/spoke2/node_modules/graphql-tools/src/schemaGenerator.ts:725:13
7:42:20 PM server.1               |      at field.resolve (/home/sky/sb/moveon/spoke2/node_modules/graphql-tools/src/mock.ts:355:13)
7:42:20 PM server.1               |      at resolveFieldValueOrError (/home/sky/sb/moveon/spoke2/node_modules/graphql/execution/execute.js:531:18)
7:42:20 PM server.1               |      at resolveField (/home/sky/sb/moveon/spoke2/node_modules/graphql/execution/execute.js:495:16)
7:42:20 PM server.1               |      at /home/sky/sb/moveon/spoke2/node_modules/graphql/execution/execute.js:364:18
7:42:20 PM server.1               |      at Array.reduce (<anonymous>)
7:42:20 PM server.1               |      at executeFields (/home/sky/sb/moveon/spoke2/node_modules/graphql/execution/execute.js:361:42)
7:42:20 PM server.1               |      at collectAndExecuteSubfields (/home/sky/sb/moveon/spoke2/node_modules/graphql/execution/execute.js:772:10)
7:42:20 PM server.1               |      at completeObjectValue (/home/sky/sb/moveon/spoke2/node_modules/graphql/execution/execute.js:762:10)
7:42:20 PM server.1               |      at completeValue (/home/sky/sb/moveon/spoke2/node_modules/graphql/execution/execute.js:660:12)
7:42:20 PM server.1               |      at /home/sky/sb/moveon/spoke2/node_modules/graphql/execution/execute.js:617:14

```

Possibly related, before creating texters, I can't seem to assign to myself (as an OWNER role)

@lperson

**Comment by schuyler1d** [comment]
actually, this is happening on https://github.com/MoveOnOrg/Spoke/pull/1154

**Comment by ibrand** [comment]
@schuyler1d does this still happen?
