### ISSUE TITLE
Make Spoke deployable on aws Lambda

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#118]
For easier scalability/cost concerns, can we make it easy to deploy on AWS lambda?

**Comment by schuyler1d** [comment]
Currently deploying successfully, but need to track down some errors and their causes:
```
=============================================================
Running handleIncomingMessages
2017-08-18T20:51:21.635Z a9bc67b4-8456-11e7-969e-fd35d3c9e367 (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'error' of undefined

==============================================================
Unhandled rejection TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
at Timeout._onTimeout (/var/task/node_modules/knex/lib/client.js:287:18)
at ontimeout (timers.js:386:14)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5)
==============================================================
2017-08-18T21:34:17.174Z 417b32ff-845c-11e7-af64-85cb237d9e39 LAMBDA EVENT { command: 'handleIncomingMessages' }
2017-08-18T21:34:18.160Z 417b32ff-845c-11e7-af64-85cb237d9e39 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'error' of undefined

==============================================================
Mailgun bad config
Error: Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.
at IncomingMessage.<anonymous> (/var/task/node_modules/mailgun-js/lib/request.js:309:15)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)

=============================================================
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Network error: fetch is not defined
=====================================================================
```

**Comment by shakalee14** [comment]
See https://github.com/MoveOnOrg/Spoke/pull/146
