### ISSUE TITLE
Bug: campaign creation creates error in logs

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#1196]
**Describe the bug**
The error console (after clicking 'create campaign' on the frontend) always yields:

```
7:52:33 PM server.1               |  .returning() is not supported by sqlite3 and will not have any effect.
7:52:33 PM server.1               |  .returning() is not supported by sqlite3 and will not have any effect.
7:52:33 PM server.1               |  .returning() is not supported by sqlite3 and will not have any effect.
7:52:33 PM server.1               |  (node:4189) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEa
7:52:33 PM server.1               |  >  ch' of undefined
7:52:33 PM server.1               |      at _callee3$ (/home/sky/sb/moveon/spoke5/src/server/api/schema.js:212:26)
7:52:33 PM server.1               |      at tryCatch (/home/sky/sb/moveon/spoke5/node_modules/babel-runtime/node_modules/
7:52:33 PM server.1               |  >  regenerator-runtime/runtime.js:62:40)
7:52:33 PM server.1               |      at Generator.invoke [as _invoke] (/home/sky/sb/moveon/spoke5/node_modules/babel-
7:52:33 PM server.1               |  >  runtime/node_modules/regenerator-runtime/runtime.js:296:22)
7:52:33 PM server.1               |      at Generator.prototype.(anonymous function) [as next] (/home/sky/sb/moveon/spoke
7:52:33 PM server.1               |  >  5/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
7:52:33 PM server.1               |      at step (/home/sky/sb/moveon/spoke5/node_modules/babel-runtime/helpers/asyncToGe
7:52:33 PM server.1               |  >  nerator.js:17:30)
7:52:33 PM server.1               |      at /home/sky/sb/moveon/spoke5/node_modules/babel-runtime/helpers/asyncToGenerato
7:52:33 PM server.1               |  >  r.js:35:14
7:52:33 PM server.1               |      at new Promise (<anonymous>)
7:52:33 PM server.1               |      at new F (/home/sky/sb/moveon/spoke5/node_modules/core-js/library/modules/_expor
7:52:33 PM server.1               |  >  t.js:36:28)
7:52:33 PM server.1               |      at /home/sky/sb/moveon/spoke5/node_modules/babel-runtime/helpers/asyncToGenerato
7:52:33 PM server.1               |  >  r.js:14:12
7:52:33 PM server.1               |      at updateInteractionSteps (/home/sky/sb/moveon/spoke5/src/server/api/schema.js:3
7:52:33 PM server.1               |  >  48:18)
7:52:33 PM server.1               |      at _callee2$ (/home/sky/sb/moveon/spoke5/src/server/api/schema.js:247:11)
7:52:33 PM server.1               |      at tryCatch (/home/sky/sb/moveon/spoke5/node_modules/babel-runtime/node_modules/
7:52:33 PM server.1               |  >  regenerator-runtime/runtime.js:62:40)
7:52:33 PM server.1               |      at Generator.invoke [as _invoke] (/home/sky/sb/moveon/spoke5/node_modules/babel-
7:52:33 PM server.1               |  >  runtime/node_modules/regenerator-runtime/runtime.js:296:22)
7:52:33 PM server.1               |      at Generator.prototype.(anonymous function) [as next] (/home/sky/sb/moveon/spoke
7:52:33 PM server.1               |  >  5/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
7:52:33 PM server.1               |      at step (/home/sky/sb/moveon/spoke5/node_modules/babel-runtime/helpers/asyncToGe
7:52:33 PM server.1               |  >  nerator.js:17:30)
7:52:33 PM server.1               |      at /home/sky/sb/moveon/spoke5/node_modules/babel-runtime/helpers/asyncToGenerato
7:52:33 PM server.1               |  >  r.js:28:13
7:52:33 PM server.1               |  (node:4189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This erro
7:52:33 PM server.1               |  >  r originated either by throwing inside of an async function without a catch block, o
7:52:33 PM server.1               |  >  r by rejecting a promise which was not handled with .catch(). (rejection id: 2)
7:52:33 PM server.1               |  (node:4189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecate
7:52:33 PM server.1               |  >  d. In the future, promise rejections that are not handled will terminate the Node.js
7:52:33 PM server.1               |  >   process with a non-zero exit code.
7:52:33 PM server.1               |  deleted result: 0
```

 - Version 03275681dcba412f8f3b1ca09523f72fcfc32df8

*Theory*

I think the key line here is: 
`/home/sky/sb/moveon/spoke5/src/server/api/schema.js:212`
which is in the updateInteractionSteps step.  I don't know why that's running on a newly created campaign -- I worry that it's because src/server/models/cacheable_queries/campaign.js *adds* a interactionSteps property to the campaign object and then in `editCampaign` it tests for that and tries to update the campaign even in 'readonly' events -- instead of skipping over that.

**Comment by schuyler1d** [comment]
This was because I was using node version `v10.15.3` but doesn't happen on 10.3 (our .nvm choice) -- so might still be worth addressing for forwards compatibility -- or maybe it's just giving more details than 10.3 is?

Feel free to close if you think this isn't worth addressing/investigating.

**Comment by schuyler1d** [comment]
resolved
