### ISSUE TITLE
Bug: Increased socket timeouts on AWS Lambda

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#1200]
**Describe the bug**
We are seeing increased errors like the following on AWS Lambda:
```
2019-08-16T19:44:28.651Z 1ec92a94-edf9-4043-b9a4-d60c3a4b24b7 { Error: socket hang up
at createHangUpError (_http_client.js:299:15)
at Socket.socketOnEnd (_http_client.js:391:23)
at emitNone (events.js:111:20)
at Socket.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' }
```
Most seem to be triggered from /twilio and /twilio-message-report
with the timeouts occuring about 2minutes after the request.

This thread:
https://github.com/awslabs/aws-serverless-express/issues/199
pointed to this thread:
https://github.com/awslabs/aws-serverless-express/issues/234#issuecomment-492559413
Which might indicate Node 10.x is the issue.

More directly, it might indicate that there is a non-`await`ed promise that is unresolved during handleIncomingMessage workflow.

**To Reproduce**
1. Deploy to lambda
2. receive messages from the /twilio endpoint
3. Possibly not all messages respond this way, so you might need volume

**Comment by ibrand** [comment]
@schuyler1d do we still see these?

**Comment by schuyler1d** [comment]
Yes but there strategy is to work around it like in https://github.com/MoveOnOrg/Spoke/pull/1352
