### ISSUE TITLE
Error Message: "There was an error in creating your invite"

### ISSUE THREAD

**Issue by rmercur1** [ProgressiveCoders/Spoke#1221]
Upon initial deployment of Spoke through Heroku, once I launch the app and click "login and get started," I'm met with the error message "There was an error in creating your invite". After scouring my auth0 settings and heroku configurations, I can't detect where the problem lies. Could someone direct me on what may be the problem?

**Comment by jeffm2001** [comment]
Same here. I've been trying to figure this out and so far no luck. From what I can tell, it doesn't look like the database tables are getting created — when I connect to postgres, the only tables that exist are _knex_migrations_ and _knex_migrations_lock_.

I do see some errors in the logs, the relevant parts of which are pasted below.

### Build Log
```
Step 8/17 : RUN yarn install --ignore-scripts --non-interactive --frozen-lockfile &&     yarn run prod-build &&     rm -rf node_modules &&     yarn install --production --ignore-scripts
 ---> Running in 0109322229dc
yarn install v1.13.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "material-ui > react-event-listener@0.6.6" has incorrect peer dependency "react@^16.3.0".
[5/5] Building fresh packages...
warning Ignored scripts due to flag.
Done in 46.31s.
yarn run v1.13.0
$ npm run clean && npm run prod-build-client && npm run prod-build-server
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1567621599579-0.8200769888633548/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> spoke@3.0.0 clean /spoke
> rm -rf $OUTPUT_DIR
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1567621599579-0.8200769888633548/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> spoke@3.0.0 prod-build-client /spoke
> webpack --config ./webpack/config.js
{ Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.config (/spoke/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/spoke/webpack/config.js:1:81)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17) errno: -2, syscall: 'open', code: 'ENOENT', path: '.env' }
Hash: b06abe8e303236c1668f
Version: webpack 3.12.0
Time: 41612ms
                         Asset      Size  Chunks                    Chunk Names
bundle.ddd4df1515b052154b8e.js   4.25 MB       0  [emitted]  [big]  bundle
                   assets.json  51 bytes          [emitted]         
  [16] (webpack)/buildin/global.js 509 bytes {0} [built]
 [946] ./src/network/apollo-client-singleton.js 1.89 kB {0} [built]
 [948] multi babel-polyfill ./src/client/index.jsx 40 bytes {0} [built]
[1150] ./src/client/index.jsx 1.8 kB {0} [built]
[1283] ./src/client/error-catcher.js 274 bytes {0} [built]
[1382] ./src/routes.jsx 10.3 kB {0} [built]
[1919] ./src/containers/AdminIncomingMessageList.jsx 28.9 kB {0} [built]
[2001] ./src/containers/AdminCampaignEdit.jsx 39.8 kB {0} [built]
[2125] ./src/containers/AdminReplySender.jsx 9.31 kB {0} [built]
[2127] ./src/containers/DashboardLoader.jsx 3.01 kB {0} [built]
[2128] ./src/containers/TexterTodoList.jsx 9 kB {0} [built]
[2130] ./src/containers/TexterTodo.jsx 14.6 kB {0} [built]
[2153] ./src/store/index.js 2.13 kB {0} [built]
[2155] ./src/network/response-middleware-network-interface.js 6.67 kB {0} [built]
[2160] ./src/client/auth-service.js 968 bytes {0} [built]
    + 2147 hidden modules
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1567621599579-0.8200769888633548/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> spoke@3.0.0 prod-build-server /spoke
> babel ./src -d ./build/server --source-maps --copy-files
```

### App Log
```
2019-09-04T18:25:01.394485+00:00 app[api]: Release v1 created by user digitaltools@aflcio.org
2019-09-04T18:29:35.698064+00:00 app[api]: Release v9 created by user digitaltools@aflcio.org
2019-09-04T18:29:35.717958+00:00 app[api]: Scaled to web@1:Free by user digitaltools@aflcio.org
2019-09-04T18:29:35.698064+00:00 app[api]: Deployed web (d86c2bc7fc57) by user digitaltools@aflcio.org
2019-09-04T18:29:35.000000+00:00 app[api]: Build succeeded
2019-09-04T18:29:45.468416+00:00 heroku[web.1]: Starting process with command `npm start`
2019-09-04T18:29:47.504259+00:00 app[web.1]: 
2019-09-04T18:29:47.504300+00:00 app[web.1]: > spoke@3.0.0 start /spoke
2019-09-04T18:29:47.504302+00:00 app[web.1]: > node ./build/server/server
2019-09-04T18:29:47.504303+00:00 app[web.1]: 
2019-09-04T18:29:52.582918+00:00 app[web.1]: [90mbackend [39m[36minfo[39m Checking if zip code is needed
2019-09-04T18:29:52.610468+00:00 app[web.1]: [90mbackend [39m[33mwarn[39m twilio webhook call
2019-09-04T18:29:52.685681+00:00 app[web.1]: [90mbackend [39m[36minfo[39m Node app is running on port 9216
2019-09-04T18:29:52.767563+00:00 app[web.1]: (node:14) UnhandledPromiseRejectionWarning: error: relation "zip_code" does not exist
2019-09-04T18:29:52.767567+00:00 app[web.1]:     at Connection.parseE (/spoke/node_modules/pg/lib/connection.js:567:11)
2019-09-04T18:29:52.767569+00:00 app[web.1]:     at Connection.parseMessage (/spoke/node_modules/pg/lib/connection.js:391:17)
2019-09-04T18:29:52.767570+00:00 app[web.1]:     at Socket.<anonymous> (/spoke/node_modules/pg/lib/connection.js:129:22)
2019-09-04T18:29:52.767575+00:00 app[web.1]:     at Socket.emit (events.js:189:13)
2019-09-04T18:29:52.767581+00:00 app[web.1]:     at Socket.EventEmitter.emit (domain.js:441:20)
2019-09-04T18:29:52.767582+00:00 app[web.1]:     at addChunk (_stream_readable.js:284:12)
2019-09-04T18:29:52.767584+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:265:11)
2019-09-04T18:29:52.767585+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:220:10)
2019-09-04T18:29:52.767587+00:00 app[web.1]:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2019-09-04T18:29:52.767631+00:00 app[web.1]: (node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-09-04T18:29:52.767703+00:00 app[web.1]: (node:14) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-09-04T18:29:52.810149+00:00 app[web.1]: CREATING DATABASE SCHEMA
2019-09-04T18:29:52.827468+00:00 app[web.1]: Unhandled rejection Error: ENOENT: no such file or directory, scandir '/spoke/migrations'
2019-09-04T18:29:53.123769+00:00 heroku[web.1]: State changed from starting to up
2019-09-04T18:30:30.804554+00:00 heroku[router]: at=info method=GET path="/" host=aflcio-spoke.herokuapp.com request_id=907fc903-ad59-4f74-b884-44c82beb5f1c fwd="12.4.17.2" dyno=web.1 connect=1ms service=42ms status=200 bytes=1902 protocol=https
2019-09-04T18:30:31.108088+00:00 heroku[router]: at=info method=POST path="/graphql" host=aflcio-spoke.herokuapp.com request_id=30dcddbb-5dfe-4f66-8c4b-b3b44d577dff fwd="12.4.17.2" dyno=web.1 connect=0ms service=48ms status=200 bytes=179 protocol=https
2019-09-04T18:30:33.698856+00:00 heroku[router]: at=info method=POST path="/graphql" host=aflcio-spoke.herokuapp.com request_id=16ef2d04-2abe-45e7-b781-70f8a57ffe69 fwd="12.4.17.2" dyno=web.1 connect=0ms service=15ms status=200 bytes=384 protocol=https
```

**Comment by jb-cloud** [comment]
Would someone mind explaining if the deploy to Heroku button option is using 3.0.0 and if it is how to update to the main branch?
