### ISSUE TITLE
Bug: Canned responses don't work with sqlite

### ISSUE THREAD

**Issue by aleffert** [ProgressiveCoders/Spoke#1269]
**Describe the bug**
When using the sqlite backend, creating canned responses does not work.

**To Reproduce**
1. Set up a user.
2. Click on campaigns.
3. Click the + button to make a new campaign.
4. Create a Canned Response
5. Hit Save
6. Refresh the page
7. Observe the Canned Response you created is not there.

**Expected behavior**
Canned response is saved in the canned responses.

**Screenshots**
None

**Platform (please complete the following information):**
 - OS: macos 10.14.6
 - Browser: Safari
 - Desktop or Mobile? Desktop
 - Version [e.g. 22]: 13.0.3

**Additional context**
The code appears to be making assumptions that aren't valid with sqlite. Got the following stack trace:

```
8:35:45 PM server.1               |  BATCH INSERT ERROR TypeError: `sqlite` does not support inserting default values. Specify values explicitly or use the `useNullAsDefault` config flag. (see docs http://knexjs.org/#Builder-insert).
8:35:45 PM server.1               |      at binding (/Users/aleffert/Documents/Source/Spoke/node_modules/knex/lib/dialects/sqlite3/query/compiler.js:65:44)
8:35:45 PM server.1               |      at arrayEach (/Users/aleffert/Documents/Source/Spoke/node_modules/lodash/lodash.js:516:11)
8:35:45 PM server.1               |      at forEach (/Users/aleffert/Documents/Source/Spoke/node_modules/lodash/lodash.js:9344:14)
8:35:45 PM server.1               |      at bindings (/Users/aleffert/Documents/Source/Spoke/node_modules/knex/lib/dialects/sqlite3/query/compiler.js:64:26)
8:35:45 PM server.1               |      at arrayEach (/Users/aleffert/Documents/Source/Spoke/node_modules/lodash/lodash.js:516:11)
8:35:45 PM server.1               |      at forEach (/Users/aleffert/Documents/Source/Spoke/node_modules/lodash/lodash.js:9344:14)
8:35:45 PM server.1               |      at QueryCompiler_SQLite3.insert (/Users/aleffert/Documents/Source/Spoke/node_modules/knex/lib/dialects/sqlite3/query/compiler.js:63:24)
8:35:45 PM server.1               |      at QueryCompiler_SQLite3.toSQL (/Users/aleffert/Documents/Source/Spoke/node_modules/knex/lib/query/compiler.js:50:29)
8:35:45 PM server.1               |      at Builder.toSQL (/Users/aleffert/Documents/Source/Spoke/node_modules/knex/lib/query/builder.js:72:44)
8:35:45 PM server.1               |      at /Users/aleffert/Documents/Source/Spoke/node_modules/knex/lib/runner.js:37:34
```

**Comment by schuyler1d** [comment]
this works
