### ISSUE TITLE
Bug: Cypress tests fail locally.

### ISSUE THREAD

**Issue by tmc** [ProgressiveCoders/Spoke#1529]
**Describe the bug**
Running cypress tests locally fails.

```
$ yarn; yarn run cypress run --browser chrome
yarn install v1.22.1
warning ../../../../../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ if [ "$NODE_ENV" = production ] ; then npm run prod-build && npm run prod-static-upload && npm run install-config-file && npm run notify-slack; fi
✨  Done in 0.87s.
yarn run v1.22.1
warning ../../../../../package.json: No license field
$ /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/.bin/cypress run --browser chrome
Knex: run
$ npm install sqlite3 --save
Cannot find module '/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/binding/electron-v8.2-darwin-x64/node_sqlite3.node'
Require stack:
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/sqlite3-binding.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/sqlite3.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/knex.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/knex.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/thinky.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/user.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/__test__/cypress/plugins/tasks.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/__test__/cypress/plugins/index.js
- /Users/user/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/user/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
Error: Cannot find module '/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/binding/electron-v8.2-darwin-x64/node_sqlite3.node'
Require stack:
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/sqlite3-binding.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/sqlite3.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/knex.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/knex.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/thinky.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/user.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/__test__/cypress/plugins/tasks.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/__test__/cypress/plugins/index.js
- /Users/user/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/user/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Object.require.extensions.<computed> [as .js] (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Object.require.extensions.<computed> [as .js] (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Client_SQLite3._driver (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/dialects/sqlite3/index.js:46:12)
    at Client_SQLite3.initializeDriver (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/client.js:253:26)
    at Client_SQLite3.Client (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/client.js:84:10)
    at new Client_SQLite3 (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/dialects/sqlite3/index.js:33:19)
    at Knex (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/knex.js:57:42)
    at new dumbThinky (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/index.js:12:27)
    at module.exports (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/index.js:123:10)
    at Object.<anonymous> (/Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/thinky.js:11:20)
The plugins file is missing or invalid.

Your `pluginsFile` is set to `/Users/user/src/github.com/MoveOnOrg/Spoke/__test__/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js` or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile` to `.ts`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

 Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/binding/electron-v8.2-darwin-x64/node_sqlite3.node'
Require stack:
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/sqlite3-binding.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/sqlite3/lib/sqlite3.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/knex.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/knex.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/thinky.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/user.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/index.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/__test__/cypress/plugins/tasks.js
- /Users/user/src/github.com/MoveOnOrg/Spoke/__test__/cypress/plugins/index.js
- /Users/user/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/user/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Client_SQLite3.initializeDriver (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/client.js:257:13)
    at Client_SQLite3.Client (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/client.js:84:10)
    at new Client_SQLite3 (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/dialects/sqlite3/index.js:33:19)
    at Knex (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/knex.js:57:42)
    at new dumbThinky (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/index.js:12:27)
    at module.exports (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/rethink-knex-adapter/index.js:123:10)
    at Object.<anonymous> (/Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/thinky.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at loader (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/user.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at loader (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/user/src/github.com/MoveOnOrg/Spoke/src/server/models/index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at loader (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/Users/user/src/github.com/MoveOnOrg/Spoke/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
```sh
yarn; yarn run cypress run --browser chrome
```

**Expected behavior**
A test run.

**Platform (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Desktop or Mobile? desktop
 - Version main and stage-main both tested

**Comment by matteosb** [comment]
It looks like the issue is that sqlite and electron (which is used by cypress) don't play nicely together. I didn't notice this because I use postgres for development. I tried some of the solutions discussed on [this thread](https://stackoverflow.com/questions/32504307/how-to-use-sqlite3-module-with-electron) but couldn't get it to work, though I admittedly didn't spend much time on it. @tmc could you check if it works for you with postgres?

We could try to get it to work with sqlite or just punt on it and have cypress fail with a descriptive error message if you are using sqlite. We could also get rid of direct database access in cypress, which we would have to do to get the test suite to run against production anyway, and instead add a separate seed script for local dev. Thoughts @schuyler1d?

**Comment by schuyler1d** [comment]
these now pass!
