### ISSUE TITLE
Bug: "Cannot read property 'message_status' of undefined" for inbound messages when the ngpvan message-handler is enabled

### ISSUE THREAD

**Issue by mayefsky** [ProgressiveCoders/Spoke#1825]
**Describe the bug**
When I enabled the ngpvan message handler, I started getting errors on incoming messages. I don't think the message handler is supposed to do anything on incoming messages and I _think_ this is harmless, but it's hard to be sure.
I am currently on 9.1 but also saw this behavior on 8.0 (I didn't have the message handler enabled in earlier verseions).

**To Reproduce**
1. enable the ngpvan message handler
2. Wait for inbound messages
3. See error

```
Sep 9 01:12:28 PM  backend error TypeError: Cannot read property 'message_status' of undefined
    at _callee$ (/spoke/build/server/extensions/message-handlers/ngpvan/index.js:57:27)
    at tryCatch (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/spoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /spoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/spoke/node_modules/core-js/library/modules/_export.js:36:28)
    at Object.<anonymous> (/spoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.postMessageSave (/spoke/build/server/extensions/message-handlers/ngpvan/index.js:90:17)
    at _callee8$ (/spoke/build/server/server/models/cacheable_queries/message.js:665:45)
    at tryCatch (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/spoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /spoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by mayefsky** [comment]
@lperson would love your take on this

**Comment by lperson** [comment]
@bobbyoderek  The van message handler should do nothing for inbound messages, so you're not losing any signals.
