### ISSUE TITLE
Bug: non-existing time zone name ''US/Eastern''

### ISSUE THREAD

**Issue by daradib** [ProgressiveCoders/Spoke#1927]
After upgrading to Spoke 10.0 and removing `DEFAULT_TZ` from the environment file, new campaigns are created with the timezone set to `'US/Eastern'` (with spurious single quotes). The texters see a blank screen with a timezone-related error in browser console or admins see a GraphQL error message when trying to edit the campaign. This is fixed by editing the campaign to remove the single quotes, either in the campaign page or by editing the campaign table in the database directly and clearing redis.

    backend error { userId: 1,
      code: 'INTERNAL_SERVER_ERROR',
      error:
       { timezonecomplete.NotFound.Zone: non-existing time zone name ''US/Eastern''
           at throwError (/spoke/node_modules/timezonecomplete/dist/lib/error.js:20:17)
           at Object.assert [as default] (/spoke/node_modules/timezonecomplete/dist/lib/assert.js:28:28)
           at new TimeZone (/spoke/node_modules/timezonecomplete/dist/lib/timezone.js:94:29)
           at Function.TimeZone._findOrCreate (/spoke/node_modules/timezonecomplete/dist/lib/timezone.js:458:21)
           at Function.TimeZone.zone (/spoke/node_modules/timezonecomplete/dist/lib/timezone.js:141:25)
           at zone (/spoke/node_modules/timezonecomplete/dist/lib/timezone.js:36:21)
           at Function.ensureTimezoneDstCalculated (/spoke/build/server/lib/dst-helper.js:44:129)
           at Function.getTimezoneOffsetHours (/spoke/build/server/lib/dst-helper.js:52:17)
           at isBetweenTextingHours (/spoke/build/server/lib/timezones.js:132:36)
           at /spoke/build/server/lib/timezones.js:174:11
           at Array.forEach (<anonymous>)
           at /spoke/build/server/lib/timezones.js:173:20
           at Array.forEach (<anonymous>)
           at getOffsets (/spoke/build/server/lib/timezones.js:172:7)
           at getCampaignOffsets (/spoke/build/server/server/api/assignment.js:89:41)
           at getContacts (/spoke/build/server/server/api/assignment.js:116:29)
           at _callee4$ (/spoke/build/server/server/api/assignment.js:461:43)
           at tryCatch (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
           at Generator.invoke [as _invoke] (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
           at Generator.prototype.(anonymous function) [as next] (/spoke/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
           at step (/spoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
           at /spoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
         message: 'non-existing time zone name \'\'US/Eastern\'\'',
         locations: [ { line: 37, column: 9 } ],
         path:
          [ 'campaign', 'texters', 0, 'assignment', 'needsMessageCount' ] },
      msg: 'GraphQL error' }

We're using Docker on Linux, not Heroku or AWS Lambda. Like the `.env.example` file, the environment file contains `DST_REFERENCE_TIMEZONE='US/Eastern'`. Docker [doesn't handle quotation marks](https://docs.docker.com/compose/env-file/) so they could become part of the value.

**Comment by schuyler1d** [comment]
There shouldn't be any quotation marks in the value.  it should just be `US/Eastern`
