### ISSUE TITLE
Error claiming invite

### ISSUE THREAD

**Issue by ben-pr-p** [ProgressiveCoders/Spoke#468]
Got an error – I have not yet been able to reproduce it, but I had run Spoke before, and the people getting it were running fresh Spoke instances. I'll try to clear my instance and reproduce later.

This was happening after redirecting back from Auth0

```
Error: Failed to serialize user into session
    at pass (/Users/nchar/Desktop/Projects/Spoke/node_modules/passport/lib/authenticator.js:271:19)
    at serialized (/Users/nchar/Desktop/Projects/Spoke/node_modules/passport/lib/authenticator.js:276:7)
    at /Users/nchar/Desktop/Projects/Spoke/src/server/setup-auth0-passport.js:18:5
    at pass (/Users/nchar/Desktop/Projects/Spoke/node_modules/passport/lib/authenticator.js:284:9)
    at Authenticator.serializeUser (/Users/nchar/Desktop/Projects/Spoke/node_modules/passport/lib/authenticator.js:289:5)
    at IncomingMessage.req.login.req.logIn (/Users/nchar/Desktop/Projects/Spoke/node_modules/passport/lib/http/request.js:50:29)
    at Strategy.strategy.success (/Users/nchar/Desktop/Projects/Spoke/node_modules/passport/lib/middleware/authenticate.js:235:13)
    at verified (/Users/nchar/Desktop/Projects/Spoke/node_modules/passport-oauth2/lib/strategy.js:177:20)
    at Strategy._verify (/Users/nchar/Desktop/Projects/Spoke/src/server/setup-auth0-passport.js:12:65)
    at /Users/nchar/Desktop/Projects/Spoke/node_modules/passport-oauth2/lib/strategy.js:191:24
    at /Users/nchar/Desktop/Projects/Spoke/node_modules/passport-auth0/lib/index.js:121:7
    at passBackControl (/Users/nchar/Desktop/Projects/Spoke/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/Users/nchar/Desktop/Projects/Spoke/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)```

**Comment by wildest** [comment]
I got this error when trying to spin up a fresh instances and register myself. The login-callback produces "Internal Server Error" then I saw this "Failed to serialize user into session" in the heroku logs.

**Comment by shakalee14** [comment]
I believe this issue was fixed with https://github.com/MoveOnOrg/Spoke/pull/483
