### ISSUE TITLE
npm install --production failing (in some environment)

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#756]
On Ubuntu Linux 14.04 an instance and setup that previously worked does not anymore.
`npm install --production`
yields
```
> spoke@1.4.0 prod-build-client /home/sky/sb/moveon/spoke2
> webpack --config ./webpack/config.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.<anonymous> (/home/sky/sb/moveon/spoke2/webpack/config.js:66:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```
This seems traceable to these lines which I don't understand (how they work, what they do, why we need them)
https://github.com/MoveOnOrg/Spoke/blob/main/webpack/config.js#L12-L15

**Comment by shakalee14** [comment]
Fixed with #759
